export const ENV_VARS_NAMES = {
    JUNIT_REPORT: {
        LOCATION: "CI_SUMMARY_JUNIT_SUMMARY_OUTPUT_PATH",
        FILTER_TEST_FAILURES_DUE_TO_DEPENDENT_CLASSES:
            "CI_SUMMARY_JUNIT_SUMMARY_EXCLUDE_TEST_FAILURES_DEPENDENTS",
    } as const,
} as const;
